### ISSUE TITLE
you can set your username to 'bot'

### ISSUE THREAD

**Issue by warandpeace** [amirrajan/nodekick#40]

**Comment by mrphlip** [comment]
Other things you can set your username to include:
* the RTL override character
* Literally a thousand rocket emoji
* The first stanza of The Raven by Edgar Allen Poe (if you change the text field on the sign-in screen to a textarea)

**Comment by warandpeace** [comment]
Can't test, but should be fixed based on a quick read of @jeremyjackson89's code.

@mrphlip I split those out into separate issues since I wasn't sure how @amirrajan'd want it to work. #16, #22, #24, #41.

**Comment by Ryan-Cooper** [comment]
Can confirm it is fixed
